[versions]
kotlin = "1.5.30"
dokka = "1.5.0"
kotlinBinaryCompatibilityValidator = "0.7.1"
kotlinCoroutines = "1.5.2"
junit5 = "5.7.2"
spek = "2.0.15"
strikt = "0.31.0"
ktlint = "10.1.0"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinCoroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinCoroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
spek-runner-junit5 = { module = "org.spekframework.spek2:spek-runner-junit5", version.ref = "spek" }
spek-dsl-jvm = { module = "org.spekframework.spek2:spek-dsl-jvm", version.ref = "spek" }
strikt-core = { module = "io.strikt:strikt-core", version.ref = "strikt" }

kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokkaGradle = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
ktlintGradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
kotlinBinaryCompatibilityValidatorGradle = { module = "org.jetbrains.kotlinx.binary-compatibility-validator:org.jetbrains.kotlinx.binary-compatibility-validator.gradle.plugin", version.ref = "kotlinBinaryCompatibilityValidator" }

[bundles]
testRuntime = ["junit-jupiter-engine", "spek-runner-junit5", "kotlin-reflect"]
testImplementation = ["junit-jupiter-api", "spek-dsl-jvm", "kotlinCoroutines-test", "strikt-core"]
