name: Publish Documentation

on:
  push:
    branches:
      - generate-kdoc-pages # FIXME Update this before merging

jobs:
  publish:
    name: Publish Documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate docs
        run: ./gradlew dokkaJekyll

      - name: Copy docs to temp directory
        run: |
          mkdir -p ~/temp/dokka
          find **/build/dokka/jekyll -mindepth 1 -maxdepth 1 | xargs -i cp -r {} ~/temp/dokka

      - name: Check out pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Replace docs
        run: |
          git rm --ignore-unmatch -r -q api
          mkdir api
          cp -r ~/temp/dokka/* api
          git add api

      - name: Commit and push
        env:
          SHA: ${{ github.sha }}
        run: |
          git commit -m "Update API documentation from $SHA"
          git log -n 1 --stat
